# A helm example values file for standard kubernetes install.
# An nginx-ingress controller is not installed and ssl isn't installed.
# Install an nginx-ingress controller
 nginx-ingress:
   Enabled: false <1>

 OperationsCenter:
   # Set the HostName for the Operation Center
   HostName: 'cloudbees-core.example.com' <2>
   # Setting ServiceType to ClusterIP creates ingress
   ServiceType: ClusterIP
   Ingress:
     tls:
     ## Set this to true in order to enable TLS on the ingress record
       Enable: false <3>
       # Create a certificate kubernetes and use it here.
       SecretName: core-example-com-tls
       Host: jenkins.cluster.local
