# A helm example values file for standard kubernetes install.
# An nginx-ingress controller is not installed and ssl isn't installed.
# Install an nginx-ingress controller
 nginx-ingress:
   Enabled: false
 OperationsCenter:
   # Set Image Version
   Image:
     dockerImage: cloudbees/cloudbees-cloud-core-oc:2.204.3.7
     dockerPullPolicy: Always
     longName: CloudBees Core - 2.204.3.7
   # Set the HostName for the Operation Center
   HostName: 'cloudbees-core-eksctl.kmedesign.com'
   # Setting ServiceType to ClusterIP creates ingress
   ServiceType: ClusterIP
   Ingress:
     tls:
     ## Set this to true in order to enable TLS on the ingress record
       Enable: false
       # Create a certificate kubernetes and use it here.
       SecretName: core-example-com-tls
       Host: jenkins.cluster.local
   CSRF:
     # This needs to be set to true for some configurations
     ProxyCompatibility: true
   JavaOpts: "Dcb.BeekeeperProp.disableIncrementalWizard=true -XX:+DisableExplicitGC -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions -verbose:gc -Xloggc:/tmp/gc.log -XX:NumberOfGCLogFiles=2 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=100m -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy -XX:ErrorFile=/tmp/hs_err_%p.log -XX:+LogVMOutput -XX:LogFile=/tmp"
 Master:
   #Set Master Image here
   Image:
     dockerImage: cloudbees/cloudbees-core-mm:2.204.3.7
     dockerPullPolicy: Always
     longName: CloudBees Core - Managed Master - 2.204.3.7
   JavaOpts: "Dcb.BeekeeperProp.disableIncrementalWizard=true -XX:+DisableExplicitGC -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions -verbose:gc -Xloggc:/tmp/gc.log -XX:NumberOfGCLogFiles=2 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=100m -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy -XX:ErrorFile=/tmp/hs_err_%p.log -XX:+LogVMOutput -XX:LogFile=/tmp"

   
 
    
