# A helm example values file for standard kubernetes install.
# An nginx-ingress controller is not installed and ssl isn't installed.
# Install an nginx-ingress controller
 nginx-ingress:
   Enabled: false
 OperationsCenter:
   # Set the HostName for the Operation Center
   HostName: 'cloudbees-core-eksctl.kmedesign.com'
   # Setting ServiceType to ClusterIP creates ingress
   ServiceType: ClusterIP
   Ingress:
     tls:
     ## Set this to true in order to enable TLS on the ingress record
       Enable: false
       # Create a certificate kubernetes and use it here.
       SecretName: core-example-com-tls
       Host: jenkins.cluster.local
   CSRF:
     # This needs to be set to true for some configurations
     ProxyCompatibility: true
   JavaOpts: "-Dcom.cloudbees.masterprovisioning.kubernetes.KubernetesMasterProvisioning.storageClassName=aws-efs -Dcb.BeekeeperProp.noFullUpgrade=true"
   Tolerations:
    - key: partition
      operator: Equal
      value: masters
      effect: NoSchedule
  NodeSelector:
    partition: "masters"
  Annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
Persistence:
  StorageClass: "aws-efs" 
 Master:
   JavaOpts: "-Dcb.BeekeeperProp.noFullUpgrade=true"
   
 
    
